service: number-in-words

frameworkVersion: ">=1.41.1"

provider:
  name: aws
  runtime: provided
  stage: dev
  region: sa-east-1
  tracing:
    lambda: true

custom:
  type: ${opt:type, 'java'}

package:
  artifact: target/function-${self:custom.type}/number-in-words-quarkus-1.0-SNAPSHOT.zip

functions:
  quarkus:
    handler: Handler
    events:
      - http:
          method: get
          path: number-in-words
